# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-15 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_faceinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
