# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-16 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_imagemodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacePlusPlusInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smile', models.FloatField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.IntegerField(default=0)),
                ('beauty_male_score', models.FloatField(default=0)),
                ('beauty_female_score', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='fpp_detected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faceplusplusinfo',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.ImageModel'),
        ),
    ]
